### ISSUE TITLE
sapper dev takes over 2 minutes to start

### ISSUE THREAD

**Issue by laurentS** [nhristov/sapper-template-rollup#7]
Hello!
Thanks for putting together a setup that includes tailwindcss, I've spent a couple hours trying to get there before finding your template :(
This works when I follow the instructions in the README, but running `yarn run dev` (which runs `sapper dev`) takes about 2.5 minutes to start on my machine. The CPU is pegged at 100% most of that time, which doesn't seem to make sense. Did I miss something, or is this slow start expected? It makes development rather painful :(
To reproduce, just follow instructions: degit, yarn install, yarn dev.

When making a trivial change in `src/routes/index.svelte` afterwards, the page refresh takes about 3 seconds.

**Comment by nhristov** [comment]
Yes, this is because **tailwindcss** does not get purged in the dev version of the build.

Here are some of the benchmarks for each scenario:

**baseline** - svelte-preprocess and tailwindcss excluded
| CMD | Time |
|-----|------|
|`npm run build`| 12.7s |
|`npm run dev`| 2.3s |
|`npm run export`| 13.0s |

**svelte-preprocess** - tailwindcss excluded
| CMD | Time |
|-----|------|
|`npm run build`| 18.7s |
|`npm run dev`| 5.6s |
|`npm run export`| 18.4s |

**tailwindcss** - full default build
| CMD | Time |
|-----|------|
|`npm run build`| 35.2s |
|`npm run dev`| 1m12s |
|`npm run export`| 36.3s |

As you can see compile time jumps to **1m12s**, however, if we disable the check ```!dev``` in **postcss.config.js** this drops down to **18.2s**

Hope this helps!

**Comment by nhristov** [comment]
Fixed in https://github.com/nhristov/sapper-template-rollup/commit/b6952f1b1f9e87490b02b2700c054eb196a15a79
